settings_version: 0.0.4
datasets_dir: C:\Users\Александр\eclipse-workspace\HackPriroda\datasets
weights_dir: weights
runs_dir: runs
uuid: 2501b1c4c20301f4c03d9733615f38f7790220831938e7e66b9651d391a4d4c2
sync: true
api_key: ''
openai_api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
